spring:
  application:
      name: HospitalMAnagementSystsem
  datasources:
    url: jdbc:mysql://localhost:3306/HotelManagementSystem
    username: root
    password: Chinta@1975
    driver-class-name: com.mysql.cj.jdbc.Driver
  jdbc:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.MySQL8Dialect
    show:
      sql: true