#spring:
 # datasource:
  #  driver-class-name: com.mysql.cj.jdbc.Driver
   # password: root@123
    #url: jdbc:mysql://localhost:3306/hotelManagementSystem
   # username: root
    #hikari:
     # maximum-pool-size: 20
      
  #jpa:
   # hibernate:
    #  ddl-auto: update
    #show-sql: true
    #database-platform: org.hibernate.dialect.MySQL8Dialect